model: "gpt-4o"
temperature: 0.0
max_tokens: 256
top_p: 1
frequency_penalty: 0
presence_penalty: 0
response_format: {"type": "json_object"}

system_prompt: |-
  I study discretionary compensation (DC) in executive compensation. My research focuses on both positive and negative adjustments within DC. I analyze sentences from SEC Form DEF 14A to determine the use of DC.

  Extract and determine:
  - `discomp`: 1 if discretionary compensation is exercised, 0 otherwise.
  - `posdiscomp`: 1 if positive discretion is exercised (when `discomp` = 1), 0 otherwise.
  - `negdiscomp`: -1 if negative discretion is exercised (when `discomp` = 1), 0 otherwise.
  - `why`: Extract sentences justifying the above values.
  
  Please provide the results in a JSON format. 

user_prompt: |-

  '''
  {{text}}
  '''
 